name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          bash ./gradlew assemble
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release Snapshot
        uses: actions/upload-artifact@v4
        with:
          name: HapticFeedBack-Release-Snapshot
          path: app/build/outputs/apk/release
          compression-level: 9

      - name: Upload Debug Snapshot
        uses: actions/upload-artifact@v4
        with:
          name: HapticFeedBack-Debug-Snapshot
          path: app/build/outputs/apk/debug
          compression-level: 9